import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Moon, ScanLine, ShieldCheck, Smartphone, Sun } from "lucide-react";
import { useTheme } from "next-themes";

import { verifyAdminMfa } from "@/lib/adminAuth";
import { StackedLogo } from "@/components/StackedLogo";
import { Logo3D } from "@/components/Logo3D";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function AdminMFA() {
  const navigate = useNavigate();
  const { theme, setTheme } = useTheme();

  const [otp, setOtp] = useState("");
  const [tempToken, setTempToken] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const storedTempToken = sessionStorage.getItem("admin_temp_token");

    if (!storedTempToken) {
      setError("Admin MFA session not found. Please log in again.");
      return;
    }

    setTempToken(storedTempToken);
  }, []);

  const handleVerify = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError("");
    setSuccess("");

    const cleanedOtp = otp.trim();

    if (!tempToken) {
      setError("Admin MFA session not found. Please log in again.");
      return;
    }

    if (!/^\d{6}$/.test(cleanedOtp)) {
      setError("Please enter a valid 6-digit OTP code.");
      return;
    }

    setLoading(true);

    try {
      const response = await verifyAdminMfa({
        temp_token: tempToken,
        otp: cleanedOtp,
      });

      sessionStorage.setItem("admin_session_token", response.admin_session_token);
      sessionStorage.removeItem("admin_temp_token");

      setSuccess("Admin MFA verified. Redirecting to dashboard...");

      setTimeout(() => {
        navigate("/admin/dashboard");
      }, 900);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Admin MFA verification failed.");
    } finally {
      setLoading(false);
    }
  };

  const handleGetQr = () => {
    setError("");
    setSuccess("");

    if (!tempToken) {
      setError("Admin MFA session not found. Please log in again.");
      return;
    }

    navigate("/admin/qr-code");
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="fixed top-0 z-50 w-full border-b border-border bg-background px-6">
        <div className="mx-auto flex h-[56px] max-w-[1200px] items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <StackedLogo size={16} />
            <span className="text-[14px] font-bold uppercase tracking-[0.08em]">
              SecureAuth
            </span>
          </Link>

          <button
            type="button"
            onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
            className="relative flex h-8 w-8 items-center justify-center text-foreground/70 hover:text-foreground"
          >
            <Sun className="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
            <Moon className="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
          </button>
        </div>
      </nav>

      <div className="min-h-screen px-6 pb-8 pt-20">
        <div className="mx-auto grid max-w-[1200px] gap-6 lg:grid-cols-[0.95fr_1.05fr]">
          <div className="relative hidden min-h-[calc(100vh-96px)] overflow-hidden pr-8 lg:flex lg:flex-col lg:justify-center">
            <div className="relative z-10">
              <p className="mb-3 text-[12px] uppercase tracking-[0.16em] text-muted-foreground">
                Admin multi-factor authentication
              </p>

              <h1 className="max-w-[560px] text-[clamp(2.3rem,4.5vw,4.6rem)] font-[500] leading-[0.96] tracking-[-0.06em]">
                Verify administrator identity before accessing monitoring data.
              </h1>

              <p className="mt-6 max-w-[500px] text-base leading-relaxed text-muted-foreground">
                Enter the time-based OTP generated by your authenticator app.
              </p>

              <div className="relative mt-8">
                <div className="pointer-events-none absolute inset-0 flex items-center justify-center opacity-35">
                  <Logo3D
                    variant={1}
                    size={430}
                    zoom={250}
                    bgHex="#0e0e10"
                    lineHex="#58585e"
                  />
                </div>

                <div className="relative z-10 grid gap-3">
                  <div className="flex items-center gap-3 rounded-sm border border-border bg-background/55 px-4 py-3 backdrop-blur-[1px]">
                    <Smartphone className="h-5 w-5 text-primary" />
                    <span className="text-sm">Authenticator app required</span>
                  </div>

                  <div className="flex items-center gap-3 rounded-sm border border-border bg-background/55 px-4 py-3 backdrop-blur-[1px]">
                    <ScanLine className="h-5 w-5 text-primary" />
                    <span className="text-sm">QR-based setup supported</span>
                  </div>

                  <div className="flex items-center gap-3 rounded-sm border border-border bg-background/55 px-4 py-3 backdrop-blur-[1px]">
                    <ShieldCheck className="h-5 w-5 text-primary" />
                    <span className="text-sm">Admin panel protected by MFA</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="flex min-h-[calc(100vh-96px)] items-center justify-center py-4">
            <Card className="w-full max-w-[560px] border-border bg-card/80 shadow-none backdrop-blur">
              <CardHeader className="space-y-4">
                <button
                  type="button"
                  onClick={() => navigate("/admin/login")}
                  className="flex w-fit items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
                >
                  <ArrowLeft className="h-4 w-4" />
                  Back to admin login
                </button>

                <div>
                  <CardTitle className="text-4xl font-medium tracking-tight">
                    Verify Admin MFA
                  </CardTitle>
                  <CardDescription className="mt-2 text-base">
                    Enter the OTP from your administrator authenticator app.
                  </CardDescription>
                </div>
              </CardHeader>

              <CardContent>
                <form onSubmit={handleVerify} className="space-y-5">
                  <div className="space-y-2">
                    <Label htmlFor="otp">OTP Code</Label>
                    <Input
                      id="otp"
                      value={otp}
                      onChange={(e) =>
                        setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))
                      }
                      placeholder="Enter 6-digit OTP"
                      inputMode="numeric"
                      maxLength={6}
                      required
                    />
                  </div>

                  {error && (
                    <div className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
                      {error}
                    </div>
                  )}

                  {success && (
                    <div className="rounded-md border border-green-500/40 bg-green-500/10 px-3 py-2 text-sm text-green-400">
                      {success}
                    </div>
                  )}

                  <div className="flex flex-col gap-3 sm:flex-row">
                    <Button type="submit" disabled={loading || !tempToken}>
                      {loading ? "Verifying..." : "Verify OTP"}
                    </Button>

                    <Button
                      type="button"
                      variant="outline"
                      onClick={handleGetQr}
                      disabled={!tempToken}
                    >
                      Get QR Code
                    </Button>
                  </div>

                  <p className="text-sm text-muted-foreground">
                    Scan the admin QR code first if your authenticator is not set up.
                  </p>
                </form>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}