import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import {
  Moon,
  Sun,
  ArrowLeft,
  ShieldCheck,
  ScanLine,
  Smartphone,
} from "lucide-react";
import { useTheme } from "next-themes";

import { verifyClientMfa } from "@/lib/clientAuth";
import { StackedLogo } from "@/components/StackedLogo";
import { Logo3D } from "@/components/Logo3D";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function MFA() {
  const navigate = useNavigate();
  const { theme, setTheme } = useTheme();

  const [otp, setOtp] = useState("");
  const [tempToken, setTempToken] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const storedTempToken = sessionStorage.getItem("client_temp_token");

    if (!storedTempToken) {
      setError("MFA session not found. Please log in again.");
      return;
    }

    setTempToken(storedTempToken);
  }, []);

  const handleVerify = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError("");
    setSuccess("");

    const cleanedOtp = otp.trim();

    if (!tempToken) {
      setError("MFA session not found. Please log in again.");
      return;
    }

    if (!/^\d{6}$/.test(cleanedOtp)) {
      setError("Please enter a valid 6-digit OTP code.");
      return;
    }

    setLoading(true);

    try {
      const response = await verifyClientMfa({
        temp_token: tempToken,
        otp: cleanedOtp,
      });

      sessionStorage.setItem("client_session_token", response.session_token);
      sessionStorage.setItem("client_login_identifier", response.username);
      sessionStorage.removeItem("client_temp_token");

      setSuccess("MFA verified successfully. Redirecting to your welcome page...");

      setTimeout(() => {
        navigate("/welcome");
      }, 1000);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Invalid MFA code. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleGetQr = () => {
    setError("");
    setSuccess("");

    if (!tempToken) {
      setError("MFA session not found. Please log in again.");
      return;
    }

    navigate("/qr-code");
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="fixed top-0 z-50 w-full border-b border-border bg-background px-6">
        <div className="mx-auto flex h-[56px] max-w-[1200px] items-center justify-between">
          <Link to="/" className="flex items-center gap-2 -ml-0.5">
            <StackedLogo size={16} />
            <span className="text-[14px] font-bold uppercase tracking-[0.08em] text-foreground">
              SecureAuth
            </span>
          </Link>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
              className="relative flex h-8 w-8 items-center justify-center text-foreground/70 transition-colors hover:text-foreground"
              title="Toggle theme"
              type="button"
            >
              <Sun className="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
              <Moon className="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
            </button>

            <button
              onClick={() => navigate("/login")}
              className="h-8 px-3 text-[13px] text-foreground/70 transition-colors hover:text-foreground"
              type="button"
            >
              Log in
            </button>
          </div>
        </div>
      </nav>

      <div className="min-h-screen px-6 pb-8 pt-20">
        <div className="mx-auto max-w-[1200px]">
          <div className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr]">
            <div className="relative hidden min-h-[calc(100vh-96px)] overflow-hidden pr-8 lg:flex lg:flex-col lg:justify-center">
              <div className="relative z-10">
                <p className="mb-3 text-[12px] uppercase tracking-[0.16em] text-muted-foreground">
                  Multi-factor authentication
                </p>

                <h1 className="max-w-[560px] text-[clamp(2.3rem,4.5vw,4.6rem)] font-[500] leading-[0.96] tracking-[-0.06em]">
                  Complete your login with a time-based authenticator code.
                </h1>

                <p className="mt-6 max-w-[500px] text-base leading-relaxed text-muted-foreground">
                  Enter the 6-digit OTP generated by your authenticator app.
                  This adds a second security layer after challenge-response login.
                </p>

                <div className="relative mt-8">
                  <div className="pointer-events-none absolute inset-0 flex items-center justify-center opacity-35">
                    <Logo3D
                      variant={1}
                      size={430}
                      zoom={250}
                      bgHex="#0e0e10"
                      lineHex="#58585e"
                    />
                  </div>

                  <div className="relative z-10 grid gap-3">
                    <div className="flex items-center gap-3 rounded-sm border border-border bg-background/55 px-4 py-3 backdrop-blur-[1px]">
                      <Smartphone className="h-5 w-5 text-primary" />
                      <span className="text-sm">Authenticator app required</span>
                    </div>

                    <div className="flex items-center gap-3 rounded-sm border border-border bg-background/55 px-4 py-3 backdrop-blur-[1px]">
                      <ScanLine className="h-5 w-5 text-primary" />
                      <span className="text-sm">QR-based TOTP setup supported</span>
                    </div>

                    <div className="flex items-center gap-3 rounded-sm border border-border bg-background/55 px-4 py-3 backdrop-blur-[1px]">
                      <ShieldCheck className="h-5 w-5 text-primary" />
                      <span className="text-sm">
                        Extra protection against account takeover
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex min-h-[calc(100vh-96px)] items-center justify-center py-4">
              <Card className="w-full max-w-[620px] border-border bg-card/80 shadow-none backdrop-blur">
                <CardHeader className="space-y-3 pb-4">
                  <button
                    type="button"
                    onClick={() => navigate("/login")}
                    className="flex w-fit items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
                  >
                    <ArrowLeft className="h-4 w-4" />
                    Back to login
                  </button>

                  <div className="space-y-2">
                    <CardTitle className="text-4xl font-medium tracking-tight">
                      Verify MFA
                    </CardTitle>

                    <CardDescription className="text-base">
                      Enter the OTP from your authenticator app to continue.
                    </CardDescription>
                  </div>
                </CardHeader>

                <CardContent>
                  <form onSubmit={handleVerify} className="space-y-6">
                    <div className="space-y-2.5">
                      <Label htmlFor="otp">OTP Code</Label>
                      <Input
                        id="otp"
                        value={otp}
                        onChange={(e) =>
                          setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))
                        }
                        placeholder="Enter 6-digit OTP"
                        inputMode="numeric"
                        maxLength={6}
                        required
                      />
                    </div>

                    {error && (
                      <div className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
                        {error}
                      </div>
                    )}

                    {success && (
                      <div className="rounded-md border border-green-500/40 bg-green-500/10 px-3 py-2 text-sm text-green-400">
                        {success}
                      </div>
                    )}

                    <div className="flex flex-col gap-3 sm:flex-row">
                      <Button
                        type="submit"
                        className="sm:min-w-40"
                        disabled={loading || !tempToken}
                      >
                        {loading ? "Verifying..." : "Verify OTP"}
                      </Button>

                      <Button
                        type="button"
                        variant="outline"
                        onClick={handleGetQr}
                        disabled={!tempToken}
                      >
                        Get QR Code
                      </Button>
                    </div>

                    <p className="text-sm text-muted-foreground">
                      If you have not scanned the QR code yet, open QR setup
                      first and then return here.
                    </p>
                  </form>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}